builds:
  - name: stellar
    env: python
    python:
      version: 3.10.13
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    runCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
